(define (problem Terran)
    (:domain Terran)
    (:objects
        VCE1 VCE2 VCE3 VCE4 VCE5 - unidad
        marine1 marine2 segador1 - unidad
        centroDeMando1 - edificio
        barracones1 extractor1 bahia1 deposito1 - edificio
        mineral1 mineral2 mineral3 gas1 gas2 - recurso
        impulsorSegador1 - investigacion

        loc1_1 loc1_2 loc1_3 loc1_4 loc1_5 loc2_1 loc2_2 loc2_3 loc2_4 loc2_5 loc3_1 loc3_2 loc3_3 loc3_4 loc3_5 loc4_1 loc4_2 loc4_3 loc4_4 loc4_5 loc5_1 loc5_2 loc5_3 loc5_4 loc5_5 - localizacion


    )
    (:init
        (conectado loc1_1 loc2_1)
        (conectado loc2_1 loc1_1)
        (conectado loc1_1 loc1_2)
        (conectado loc1_2 loc1_1)
        (conectado loc1_2 loc2_2)
        (conectado loc2_2 loc1_2)
        (conectado loc1_2 loc1_3)
        (conectado loc1_3 loc1_2)
        (conectado loc1_2 loc1_1)
        (conectado loc1_1 loc1_2)
        (conectado loc1_3 loc2_3)
        (conectado loc2_3 loc1_3)
        (conectado loc1_3 loc1_4)
        (conectado loc1_4 loc1_3)
        (conectado loc1_3 loc1_2)
        (conectado loc1_2 loc1_3)
        (conectado loc1_4 loc2_4)
        (conectado loc2_4 loc1_4)
        (conectado loc1_4 loc1_5)
        (conectado loc1_5 loc1_4)
        (conectado loc1_4 loc1_3)
        (conectado loc1_3 loc1_4)
        (conectado loc1_5 loc2_5)
        (conectado loc2_5 loc1_5)
        (conectado loc1_5 loc1_4)
        (conectado loc1_4 loc1_5)
        (conectado loc2_1 loc1_1)
        (conectado loc1_1 loc2_1)
        (conectado loc2_1 loc3_1)
        (conectado loc3_1 loc2_1)
        (conectado loc2_1 loc2_2)
        (conectado loc2_2 loc2_1)
        (conectado loc2_2 loc1_2)
        (conectado loc1_2 loc2_2)
        (conectado loc2_2 loc3_2)
        (conectado loc3_2 loc2_2)
        (conectado loc2_2 loc2_3)
        (conectado loc2_3 loc2_2)
        (conectado loc2_2 loc2_1)
        (conectado loc2_1 loc2_2)
        (conectado loc2_3 loc1_3)
        (conectado loc1_3 loc2_3)
        (conectado loc2_3 loc3_3)
        (conectado loc3_3 loc2_3)
        (conectado loc2_3 loc2_4)
        (conectado loc2_4 loc2_3)
        (conectado loc2_3 loc2_2)
        (conectado loc2_2 loc2_3)
        (conectado loc2_4 loc1_4)
        (conectado loc1_4 loc2_4)
        (conectado loc2_4 loc3_4)
        (conectado loc3_4 loc2_4)
        (conectado loc2_4 loc2_5)
        (conectado loc2_5 loc2_4)
        (conectado loc2_4 loc2_3)
        (conectado loc2_3 loc2_4)
        (conectado loc2_5 loc1_5)
        (conectado loc1_5 loc2_5)
        (conectado loc2_5 loc3_5)
        (conectado loc3_5 loc2_5)
        (conectado loc2_5 loc2_4)
        (conectado loc2_4 loc2_5)
        (conectado loc3_1 loc2_1)
        (conectado loc2_1 loc3_1)
        (conectado loc3_1 loc4_1)
        (conectado loc4_1 loc3_1)
        (conectado loc3_1 loc3_2)
        (conectado loc3_2 loc3_1)
        (conectado loc3_2 loc2_2)
        (conectado loc2_2 loc3_2)
        (conectado loc3_2 loc4_2)
        (conectado loc4_2 loc3_2)
        (conectado loc3_2 loc3_3)
        (conectado loc3_3 loc3_2)
        (conectado loc3_2 loc3_1)
        (conectado loc3_1 loc3_2)
        (conectado loc3_3 loc2_3)
        (conectado loc2_3 loc3_3)
        (conectado loc3_3 loc4_3)
        (conectado loc4_3 loc3_3)
        (conectado loc3_3 loc3_4)
        (conectado loc3_4 loc3_3)
        (conectado loc3_3 loc3_2)
        (conectado loc3_2 loc3_3)
        (conectado loc3_4 loc2_4)
        (conectado loc2_4 loc3_4)
        (conectado loc3_4 loc4_4)
        (conectado loc4_4 loc3_4)
        (conectado loc3_4 loc3_5)
        (conectado loc3_5 loc3_4)
        (conectado loc3_4 loc3_3)
        (conectado loc3_3 loc3_4)
        (conectado loc3_5 loc2_5)
        (conectado loc2_5 loc3_5)
        (conectado loc3_5 loc4_5)
        (conectado loc4_5 loc3_5)
        (conectado loc3_5 loc3_4)
        (conectado loc3_4 loc3_5)
        (conectado loc4_1 loc3_1)
        (conectado loc3_1 loc4_1)
        (conectado loc4_1 loc5_1)
        (conectado loc5_1 loc4_1)
        (conectado loc4_1 loc4_2)
        (conectado loc4_2 loc4_1)
        (conectado loc4_2 loc3_2)
        (conectado loc3_2 loc4_2)
        (conectado loc4_2 loc5_2)
        (conectado loc5_2 loc4_2)
        (conectado loc4_2 loc4_3)
        (conectado loc4_3 loc4_2)
        (conectado loc4_2 loc4_1)
        (conectado loc4_1 loc4_2)
        (conectado loc4_3 loc3_3)
        (conectado loc3_3 loc4_3)
        (conectado loc4_3 loc5_3)
        (conectado loc5_3 loc4_3)
        (conectado loc4_3 loc4_4)
        (conectado loc4_4 loc4_3)
        (conectado loc4_3 loc4_2)
        (conectado loc4_2 loc4_3)
        (conectado loc4_4 loc3_4)
        (conectado loc3_4 loc4_4)
        (conectado loc4_4 loc5_4)
        (conectado loc5_4 loc4_4)
        (conectado loc4_4 loc4_5)
        (conectado loc4_5 loc4_4)
        (conectado loc4_4 loc4_3)
        (conectado loc4_3 loc4_4)
        (conectado loc4_5 loc3_5)
        (conectado loc3_5 loc4_5)
        (conectado loc4_5 loc5_5)
        (conectado loc5_5 loc4_5)
        (conectado loc4_5 loc4_4)
        (conectado loc4_4 loc4_5)
        (conectado loc5_1 loc4_1)
        (conectado loc4_1 loc5_1)
        (conectado loc5_1 loc5_2)
        (conectado loc5_2 loc5_1)
        (conectado loc5_2 loc4_2)
        (conectado loc4_2 loc5_2)
        (conectado loc5_2 loc5_3)
        (conectado loc5_3 loc5_2)
        (conectado loc5_2 loc5_1)
        (conectado loc5_1 loc5_2)
        (conectado loc5_3 loc4_3)
        (conectado loc4_3 loc5_3)
        (conectado loc5_3 loc5_4)
        (conectado loc5_4 loc5_3)
        (conectado loc5_3 loc5_2)
        (conectado loc5_2 loc5_3)
        (conectado loc5_4 loc4_4)
        (conectado loc4_4 loc5_4)
        (conectado loc5_4 loc5_5)
        (conectado loc5_5 loc5_4)
        (conectado loc5_4 loc5_3)
        (conectado loc5_3 loc5_4)
        (conectado loc5_5 loc4_5)
        (conectado loc4_5 loc5_5)
        (conectado loc5_5 loc5_4)
        (conectado loc5_4 loc5_5)

        (en VCE1 loc2_4 )
        (en centroDeMando1 loc2_4 )
        (en gas1 loc2_3)
        (en gas2 loc4_1)
        (en mineral1 loc2_2)
        (en mineral2 loc3_5)
        (en mineral3 loc2_4)

        (esUnidad VCE1 VCE)
        (esUnidad VCE2 VCE)
        (esUnidad VCE3 VCE)
        (esUnidad marine1 marines)
        (esUnidad marine2 marines)
        (esUnidad segador1 segadores)
        (esRecurso mineral1 mineral)
        (esRecurso mineral2 mineral)
        (esRecurso mineral3 mineral)
        (esRecurso gas1 gas)
        (esRecurso gas2 gas)
        (esEdificio centroDeMando1 centroDeMando)
        (esEdificio barracones1 barracones)
        (esEdificio extractor1 extractor)
        (esEdificio bahia1 bahiaDeIngenieria)
        (esEdificio deposito1 deposito)
        (esInvestigacion impulsorSegador1 impulsorSegador)

        (creadoEn marines barracones)
        (creadoEn segadores barracones)
        (creadoEn VCE centroDeMando)

        (unidadCreada VCE1)
        (unidadLibre VCE1)

        (locLibreEdif loc1_1)
        (locLibreEdif loc1_2)
        (locLibreEdif loc1_3)
        (locLibreEdif loc1_4)
        (locLibreEdif loc1_5)
        (locLibreEdif loc2_1)
        (locLibreEdif loc2_2)
        (locLibreEdif loc2_3)
        (locLibreEdif loc2_5)
        (locLibreEdif loc3_1)
        (locLibreEdif loc3_2)
        (locLibreEdif loc3_3)
        (locLibreEdif loc3_4)
        (locLibreEdif loc3_5)
        (locLibreEdif loc4_1)
        (locLibreEdif loc4_2)
        (locLibreEdif loc4_3)
        (locLibreEdif loc4_4)
        (locLibreEdif loc4_5)
        (locLibreEdif loc5_1)
        (locLibreEdif loc5_2)
        (locLibreEdif loc5_3)
        (locLibreEdif loc5_4)
        (locLibreEdif loc5_5)

        (= (numAsignados mineral1) 0)
        (= (numAsignados mineral2) 0)
        (= (numAsignados mineral3) 0)
        (= (numAsignados gas1) 0)
        (= (numAsignados gas2) 0)

        (= (necesario centroDeMando mineral) 150)
        (= (necesario centroDeMando gas) 50)
        (= (necesario barracones mineral) 150)
        (= (necesario barracones gas) 0)
        (= (necesario extractor mineral) 75)
        (= (necesario extractor gas) 0)
        (= (necesario bahiaDeIngenieria mineral) 125)
        (= (necesario bahiaDeIngenieria gas) 0)
        (= (necesario deposito mineral) 75)
        (= (necesario deposito gas) 25)
        (= (necesario marines mineral) 50)
        (= (necesario marines gas) 0)
        (= (necesario segadores mineral) 50)
        (= (necesario segadores gas) 50)
        (= (necesario VCE mineral) 50)
        (= (necesario VCE gas) 0)
        (= (necesario impulsorSegador mineral) 50)
        (= (necesario impulsorSegador gas) 200)
        (= (capacidad gas) 100)
        (= (capacidad mineral) 100)
        (= (disponible gas) 0)
        (= (disponible mineral) 0)


    )
    (:goal
        (and
            (en marine1 loc4_3)
	        (en marine2 loc5_5)
            (en segador1 loc5_5)
        )
    )
)
